name: Screenshot
on: 
  issue_comment:
    types: 
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout main
      uses: actions/checkout@v2
    - name: start server
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
      - run: npm run start & npx wait-on 172.17.0.1:3000
    - name: js action
      uses: ./sc-action
      with:
        who-to-greet: 'Mona the Octocat'
